### ISSUE TITLE
Issues with Images

### ISSUE THREAD

**Issue by Boxkin** [1ForeverHD/TopbarPlus#26]
For some reason Images do not upload properly, I know that It's just me messing up but please help me, Script for the part below:

local Icon = require(game:GetService("ReplicatedStorage").Icon)

Icon.new()
:setImage(6878002842)
:setLabel("")

**Comment by 1ForeverHD** [comment]
Make sure to use the AssetId instead of the WebsiteId.

An easy way to convert a WebsiteId into an AssetId is by pasting it into the Texture property of a Decal for instance.

You can also get the AssetId by right clicking an item in the toolbox!

![image](https://user-images.githubusercontent.com/51117782/120059548-36891b00-c04a-11eb-9b3e-6db7f4737744.png)
