### ISSUE TITLE
Horizontal Menu Clipping When setRight() Type:Bug

### ISSUE THREAD

**Issue by Inctus** [1ForeverHD/TopbarPlus#59]
## Reproduction Code and Place Link

*Repro place: https://www.roblox.com/games/10845077955/TopbarPlus-Menu-Reproduction*

```lua
Icon.new():setMenu({
    Icon.new();
    Icon.new();
}):setRight()
```

## Description of Issue | Proposed General Fix

When the position of a menu changes with `:setRight`, `:setLeft`, `:setMid`, it should reconcile and update the menu opening direction automatically.

**Comment by Inctus** [comment]
### Example Code that Works
```lua
Icon.new():setRight():setMenu({
    Icon.new();
    Icon.new();
})

**Comment by 1ForeverHD** [comment]
Thanks Inctus! Your repo and issue details are incredibly helpful. I'll look at having this fixed. For now this will be labelled low priority as users can manually fix it theirselves. 

Details for future reference:

Expected behaviour:
https://user-images.githubusercontent.com/51117782/188871131-cf9149dd-f873-4609-9501-81a8afcc5fa7.mp4

Actual behaviour:
https://user-images.githubusercontent.com/51117782/188871185-924c8e3d-b20a-4749-ba38-35514d0d4919.mp4

To fix temporarily:
Call ``:setRight`` before calling ``:setMenu``
