### ISSUE TITLE
Using TopbarPlus :setRight() breaks deploying roblox's damage effect on screen (happens at Playground game as well)

### ISSUE THREAD

**Issue by CJStyles123** [1ForeverHD/TopbarPlus#66]
After trying to fix an issue on why damage effect doesn't show up when a player gets damaged it has come to a conclusion that this issue is from TopbarPlus itself.

(This issue also happens on the Playground game too!)

Edit: this only happens if icons use the :setRight()

Since you made a health gui to fit right with the topbar buttons you think you can do a damage effect similar to how roblox does it?

**Comment by CJStyles123** [comment]
I wish i could get back the time of me trying to find out why roblox's damage effect wouldn't show up, had to disable so many server scripts to try and see if those were the issues even though i didn't change anything. oh well...

**Comment by 1ForeverHD** [comment]
Hi CJ, you're right that the damage effect is disabled when an icon is set to the right. This happens because the Health CoreGui is disabled so that the custom healthbar can be shown instead (which dynamically moves with the icons unlike the default Roblox one) and unfortunately the damage effect is also internally disabled when this happens:

![image](https://user-images.githubusercontent.com/51117782/203831466-8ecf195a-c9d9-482b-9c5f-4478b4af8458.png)

Is there an important reason you need the damage effect?

Have you explored making your own damage effect?
https://www.youtube.com/watch?v=-hzDdv4sybA

**Comment by CJStyles123** [comment]
> Is there an important reason you need the damage effect?

Yes, Basically we own a wrestling group that relies on sword-like tools. The problem is people complain saying they didn't realize their health was going down due to the damage effect not being shown which prompts our developers to look for almost an hour to see if there was a script inside the game breaking the damage effect which has concluded our investigation it being the topbar plus.

> Have you explored making your own damage effect?

Correct, But we wanted to check up with you if there was any other workarounds. We'll be working on this soon.

I appreciate your response and im looking forward to the nanoblox admin sometime (I heard it was going to release at the end of 2021 but it's better delaying a project then having a rushed one!).

I appreciate your response HD!
